/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg4_student_score;

import javax.swing.JOptionPane;

/**
 *
 * @author Riza Hariati
 */
public class ScoreForm extends javax.swing.JFrame {

    /**
     * Creates new form ScoreForm
     */
    public ScoreForm() {

        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nilaiMatematika = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nilaiBahasaIndonesia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nilaiBahasaInggris = new javax.swing.JTextField();
        hitungBtn = new javax.swing.JButton();
        hapusBtn = new javax.swing.JButton();
        alert = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Data Nilai Siswa");
        setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        setMinimumSize(new java.awt.Dimension(600, 400));

        mainPanel.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        mainPanel.setPreferredSize(new java.awt.Dimension(600, 350));
        mainPanel.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DATA NILAI SISWA");
        mainPanel.add(jLabel2);
        jLabel2.setBounds(160, 30, 280, 50);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel3.setText("Nama Lengkap");
        mainPanel.add(jLabel3);
        jLabel3.setBounds(80, 90, 160, 30);

        nama.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        nama.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nama.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        mainPanel.add(nama);
        nama.setBounds(240, 90, 270, 30);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel4.setText("Nilai Matematika");
        mainPanel.add(jLabel4);
        jLabel4.setBounds(80, 130, 160, 30);

        nilaiMatematika.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        nilaiMatematika.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nilaiMatematika.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        mainPanel.add(nilaiMatematika);
        nilaiMatematika.setBounds(240, 130, 270, 30);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel5.setText("Nilai Bahasa Indonesia");
        mainPanel.add(jLabel5);
        jLabel5.setBounds(80, 170, 160, 30);

        nilaiBahasaIndonesia.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        nilaiBahasaIndonesia.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nilaiBahasaIndonesia.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        mainPanel.add(nilaiBahasaIndonesia);
        nilaiBahasaIndonesia.setBounds(240, 170, 270, 30);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel6.setText("Nilai Bahasa Inggris");
        mainPanel.add(jLabel6);
        jLabel6.setBounds(80, 210, 160, 30);

        nilaiBahasaInggris.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        nilaiBahasaInggris.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nilaiBahasaInggris.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        mainPanel.add(nilaiBahasaInggris);
        nilaiBahasaInggris.setBounds(240, 210, 270, 30);

        hitungBtn.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        hitungBtn.setText("Hitung");
        hitungBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hitungBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungBtnActionPerformed(evt);
            }
        });
        mainPanel.add(hitungBtn);
        hitungBtn.setBounds(300, 280, 130, 30);

        hapusBtn.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        hapusBtn.setText("Hapus");
        hapusBtn.setToolTipText("");
        hapusBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtnActionPerformed(evt);
            }
        });
        mainPanel.add(hapusBtn);
        hapusBtn.setBounds(160, 280, 130, 30);

        alert.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        alert.setForeground(new java.awt.Color(255, 51, 51));
        alert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainPanel.add(alert);
        alert.setBounds(80, 250, 430, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hitungBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungBtnActionPerformed
        // TODO add your handling code here:
        alert.setText("");
        String nm;
        String mtk;
        String bhsIndonesia;
        String bhsInggris;
        if (nama.getText().equals("") || nilaiMatematika.getText().equals("")
                || nilaiBahasaIndonesia.getText().equals("")
                || nilaiBahasaInggris.getText().equals("")) {
            alert.setText("Ada input yang belum terisi");
        } else {
            nm = nama.getText();
            mtk = nilaiMatematika.getText();
            bhsIndonesia = nilaiBahasaIndonesia.getText();
            bhsInggris = nilaiBahasaInggris.getText();

            int nilaiMtk = Integer.parseInt(mtk);
            int nilaiBhs = Integer.parseInt(bhsIndonesia);
            int nilaiIng = Integer.parseInt(bhsInggris);
            int average = (nilaiBhs + nilaiIng + nilaiMtk) / 3;
            String score = "";
            if (average >= 75) {
                score = "Hebat! ";
            } else if (average < 75 && average > 50) {
                score = "Selamat, ";
            } else {
                score = "Maaf, ";
            }

            JOptionPane.showMessageDialog(this, score + nm + "\n Nilai rata-rata Anda :" + average, 
                    "score", JOptionPane.CANCEL_OPTION);

        }
    }//GEN-LAST:event_hitungBtnActionPerformed

    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed

// TODO add your handling code here:
        nama.setText("");
        nilaiBahasaIndonesia.setText("");
        nilaiBahasaInggris.setText("");
        nilaiMatematika.setText("");
        alert.setText("Semua sudah dihapus");

    }//GEN-LAST:event_hapusBtnActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_namaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alert;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JButton hitungBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nilaiBahasaIndonesia;
    private javax.swing.JTextField nilaiBahasaInggris;
    private javax.swing.JTextField nilaiMatematika;
    // End of variables declaration//GEN-END:variables
}
